### ISSUE TITLE
[Feature Request] WebView优化

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#1059]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

计划异步初始化来实现
或者使用池化技术
考虑新增WebViewUtil

**Comment by unknowIfGuestInDream** [comment]
https://blog.csdn.net/xingyu19911016/article/details/121361622#:~:text=%E5%8F%AF%E4%BB%A5%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%90%AF%E5%8A%A8,%E7%9A%84%E9%A6%96%E6%AC%A1%E6%89%93%E5%BC%80%E6%97%B6%E9%97%B4%E3%80%82

**Comment by unknowIfGuestInDream** [comment]
https://gitee.com/missyouch/desserts/blob/master/src/main/java/cerebrum/common/OsUtil.java
https://blog.csdn.net/lingyancangqiong/article/details/112879242

**Comment by unknowIfGuestInDream** [comment]
```java
webEngine.getLoadWorker().stateProperty()
        .addListener(new ChangeListener<State>() {
   
          @Override
          public void changed(ObservableValue ov, State oldState, State newState) {
   

            if (newState == Worker.State.SUCCEEDED) {
   
              stage.setTitle(webEngine.getLocation());
            }

          }
        });
```

**Comment by unknowIfGuestInDream** [comment]
https://cloud.tencent.com/developer/article/1625230

**Comment by unknowIfGuestInDream** [comment]
https://zhuanlan.zhihu.com/p/451342438

**Comment by unknowIfGuestInDream** [comment]
https://vimsky.com/examples/usage/javafx-webview-class.html

**Comment by unknowIfGuestInDream** [comment]
https://www.cnblogs.com/qingmiaokeji/p/10893897.html

**Comment by DreamAwakenFateBroke** [comment]
初始化异步初始化后再将组件放到UI上
