### ISSUE TITLE
[Feature Request] 用户数据方案

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#129]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

需要对应版本号，如果版本号不同则考虑清除数据
计划在每个组件中加版本号方便数据管理

**Comment by unknowIfGuestInDream** [comment]
考虑新增getConponmentId 接口

**Comment by unknowIfGuestInDream** [comment]
#40

**Comment by DreamAwakenFateBroke** [comment]
版本号不同的解决方案
