### ISSUE TITLE
[Feature Request] specGeneral 头文件生成多行注释增强

### ISSUE THREAD

**Issue by DreamAwakenFateBroke** [unknowIfGuestInDream/javafxTool#359]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

存在多行注释时判断文本位置
符合多行注释规范

**Comment by unknowIfGuestInDream** [comment]
增加只生成文件的checkbox 默认false
