### ISSUE TITLE
[Feature Request] 菜单树右键菜单设置

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#444]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

https://github.com/Naton1/jvm-explorer/blob/master/explorer/src/main/java/com/github/naton1/jvmexplorer/fx/classes/ClassCellFactory.java

**Comment by DreamAwakenFateBroke** [comment]
https://blog.csdn.net/qq_63141702/article/details/128693500

**Comment by unknowIfGuestInDream** [comment]
CellFactory  提供抽象类让子类重写，新增返回默认treeCell接口，Default实现
