### ISSUE TITLE
[Feature Request] qe html转码

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#475]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

todo

**Comment by DreamAwakenFateBroke** [comment]
https://hutool.cn/docs/#/http/HTML%E5%B7%A5%E5%85%B7%E7%B1%BB-HtmlUtil?id=%e7%94%b1%e6%9d%a5
