### ISSUE TITLE
[Feature Request] groovy集成

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#503]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

http://www.groovy-lang.org/documentation.html

**Comment by unknowIfGuestInDream** [comment]
https://www.cnblogs.com/Ming8006/p/10870696.html

**Comment by unknowIfGuestInDream** [comment]
https://www.cnblogs.com/jizha/p/5027695.html

**Comment by DreamAwakenFateBroke** [comment]
excel操作

https://www.codenong.com/8057870/
https://github.com/ssadedin/excelcatgory

**Comment by unknowIfGuestInDream** [comment]
https://blog.csdn.net/feiqinbushizheng/article/details/108580652

**Comment by unknowIfGuestInDream** [comment]
https://juejin.cn/post/6932778923491065864
