### ISSUE TITLE
[Feature Request] 新增sample对fxml的支持

### ISSUE THREAD

**Issue by DreamAwakenFateBroke** [unknowIfGuestInDream/javafxTool#583]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在Qe中实现， 计划添加测试类

**Comment by unknowIfGuestInDream** [comment]
https://zq99299.github.io/note-book/posts/java/javafx/#%E7%A8%8B%E5%BA%8F%E6%9C%80%E5%B0%8F%E5%8C%96%E5%88%B0%E6%89%98%E7%9B%98
