### ISSUE TITLE
[Feature Request] qe js/css compress需要功能描述

### ISSUE THREAD

**Issue by DreamAwakenFateBroke** [unknowIfGuestInDream/javafxTool#763]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

getControlPane接口实现

**Comment by unknowIfGuestInDream** [comment]
此外需要拖拽输入内容功能

**Comment by unknowIfGuestInDream** [comment]
FileChooserUtil 新增设置内容的方法
